spring.application.name=subscription-service

spring.datasource.url=jdbc:mysql://localhost:3306/subscription_application
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 

jwt.secret=bXlfc3Ryb25nX3NlY3JldGVfa2V5X29mXzMyX2J5dGVz
jwt.access.expiration=900000